apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
spec:
  entrypoint: hello-world
  templates:
    - name: hello-world
      steps:
      - - name: "hello-world-default"
          template: whalesay
          arguments:
            parameters:
            - name: message
              value: "Hello world from default node"  
        - name: "hello-world-with-node"
          template: "whalesay-node"
          arguments:
            parameters:
            - name: message
              value: "hello1"
    - name: whalesay-node
      nodeSelector:
        role: "{{workflow.name}}"
      tolerations:
        - key: role
          operator: Equal
          value: "{{workflow.name}}"
          effect: NoSchedule
      inputs:
        parameters:
        - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
    - name: whalesay
      inputs:
        parameters:
        - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
