{{- if .Values.ingress.kong.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/jawadqur/gen3-argo-gitops.git'
      targetRevision: master
      path: bootstrap/charts/kong/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kong
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
{{- end }}