apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/uc-cdis/cloud-automation.git'
      targetRevision: master
      ref: cloudautomation
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 48.1.1
      helm:
        skipCrds: true
        valueFiles: 
        - $cloudautomation/kube/services/monitoring/values.yaml
        releaseName: prometheus
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true