apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/jawadqur/gen3-argo-gitops.git'
      targetRevision: master
      ref: values
    - repoURL: 'https://github.com/uc-cdis/cloud-automation.git'
      targetRevision: master
      ref: cloudautomation
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 43.1.3
      helm:
        skipCrds: true
        valueFiles: 
        - $values/cluster-resources/values/kube-prometheus-values.yaml
        releaseName: prometheus
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true