apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm.git
      targetRevision: feat/GPE-979
      helm:
        releaseName: gen3
        valueFiles:
          - $values/qureshi.planx-pla.net/values/gen3.yaml
          - $values/qureshi.planx-pla.net/values/fence.yaml
          - $values/qureshi.planx-pla.net/values/portal.yaml
          - $values/qureshi.planx-pla.net/values/hatchery.yaml
          - $values/qureshi.planx-pla.net/values/guppy.yaml
    - repoURL: 'https://github.com/jawadqur/gen3-argo-gitops.git'
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
