apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/jawadqur/gen3-argo-gitops.git'
      targetRevision: master
      ref: values
    - chart: opensearch
      repoURL: https://opensearch-project.github.io/helm-charts/
      targetRevision: 2.13.1
      helm:
        releaseName: opensearch
        valueFiles:
          - $values/qureshi.planx-pla.net/values/opensearch.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true