apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelmetry
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/jawadqur/gen3-argo-gitops.git
    path: opentelemetry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

